import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { deploy } from '../src/api'
import { KVNamespace } from '../src/resources/kv'
import { Worker } from '../src/resources/worker'

interface RecordedRequest {
	url: string
	method: string
	body: unknown
}

const installFetchMock = () => {
	const requests: RecordedRequest[] = []
	const originalFetch = globalThis.fetch

	globalThis.fetch = (async (input: RequestInfo | URL, init?: RequestInit) => {
		const url = typeof input === 'string' ? input : input.toString()
		const method = init?.method ?? 'GET'
		const body = init?.body ? JSON.parse(init.body as string) : undefined
		requests.push({ url, method, body })

		// state read: bulk/get returns no stored state -> fresh state
		const ok = (result: unknown) =>
			new Response(JSON.stringify({ success: true, result }), {
				status: 200,
				headers: { 'Content-Type': 'application/json' },
			})

		if (url.includes('/bulk/get')) {
			return ok({ values: {} })
		}
		return ok({})
	}) as typeof fetch

	return {
		requests,
		restore() {
			globalThis.fetch = originalFetch
		},
	}
}

describe('deploy (programmatic API)', () => {
	let mock: ReturnType<typeof installFetchMock>

	beforeEach(() => {
		mock = installFetchMock()
	})

	afterEach(() => {
		mock.restore()
	})

	test('provisions a simple worker and returns the generated config', async () => {
		const definition = new Worker({
			dir: '/tmp/oblaka-api-test',
			name: 'test-worker',
			compatibility_flags: ['nodejs_compat'],
			bindings: {
				KV: new KVNamespace({ name: 'my-kv' }),
			},
			main: './src/index.ts',
		})

		const result = await deploy(definition, {
			accountId: 'acc-123',
			apiToken: 'token-abc',
			env: 'production',
			stateNamespaceId: 'state-kv-id',
			dryRun: true,
		})

		// config is produced; the applier provisions the worker so the name is env-prefixed
		expect(result.wranglerConfig).toBeDefined()
		expect(result.wranglerConfig?.name).toBe('production-test-worker')
		expect(result.wranglerConfig?.compatibility_flags).toEqual(['nodejs_compat'])
		expect(result.wranglerConfig?.main).toBe('./src/index.ts')

		// kv binding wired into the config (dry-run id is generated by the applier)
		expect(result.wranglerConfig?.kv_namespaces).toHaveLength(1)
		expect(result.wranglerConfig?.kv_namespaces?.[0].binding).toBe('KV')

		expect(result.wranglerConfigs).toHaveLength(1)
		expect(result.wranglerConfigs[0].path).toBe('/tmp/oblaka-api-test/wrangler.jsonc')

		// state was read from the provided KV namespace (no namespace listing because id supplied)
		const stateRead = mock.requests.find(r => r.url.includes('/storage/kv/namespaces/state-kv-id/bulk/get'))
		expect(stateRead).toBeDefined()
		expect(stateRead?.body).toEqual({ keys: ['production'] })

		// dry-run: no resource provisioning calls, no state write
		expect(mock.requests.some(r => r.url.includes('/workers/workers'))).toBe(false)
		expect(mock.requests.some(r => r.method === 'PUT' && r.url.includes('/values/'))).toBe(false)
	})

	test('returns config for nested child workers', async () => {
		const definition = new Worker({
			dir: '/tmp/oblaka-api-parent',
			name: 'parent-worker',
			compatibility_flags: ['nodejs_compat'],
			bindings: {
				CHILD: new Worker({
					dir: '/tmp/oblaka-api-child',
					name: 'child-worker',
					compatibility_flags: ['nodejs_compat'],
					bindings: {},
				}),
			},
		})

		const result = await deploy(definition, {
			accountId: 'acc-123',
			apiToken: 'token-abc',
			env: 'production',
			stateNamespaceId: 'state-kv-id',
			dryRun: true,
		})

		expect(result.wranglerConfigs).toHaveLength(2)
		expect(result.wranglerConfig?.name).toBe('production-parent-worker')
		expect(result.wranglerConfig?.services).toEqual([{ binding: 'CHILD', service: 'production-child-worker' }])

		const childConfig = result.wranglerConfigs[1].config
		expect(childConfig.name).toBe('production-child-worker')
	})

	test('returns empty result for undefined definition', async () => {
		const result = await deploy(undefined, {
			accountId: 'acc-123',
			apiToken: 'token-abc',
			env: 'production',
			stateNamespaceId: 'state-kv-id',
			dryRun: true,
		})

		expect(result.wranglerConfigs).toHaveLength(0)
		expect(result.wranglerConfig).toBeUndefined()
	})
})
